CREATE TABLE work_order (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code  VARCHAR(50)  NOT NULL,
    quantity      INTEGER      NOT NULL,
    country_code  VARCHAR(2)   NOT NULL,
    start_date    DATE         NOT NULL,
    due_date      DATE         NOT NULL,
    required_days INTEGER      NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PLANNED',
    risk_flag     VARCHAR(10),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_work_order_filters ON work_order (status, country_code, risk_flag);

CREATE TABLE holiday_cache (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code  VARCHAR(2)   NOT NULL,
    holiday_year  INTEGER      NOT NULL,
    holiday_date  DATE         NOT NULL,
    holiday_name  VARCHAR(150),
    fetched_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_holiday_cache_country_year_date
    ON holiday_cache (country_code, holiday_year, holiday_date);

CREATE TABLE holiday_sync (
    country_code    VARCHAR(2)  NOT NULL,
    holiday_year    INTEGER     NOT NULL,
    last_attempt_at TIMESTAMP   NOT NULL,
    last_success_at TIMESTAMP,
    last_outcome    VARCHAR(10) NOT NULL,
    PRIMARY KEY (country_code, holiday_year)
);
